nexy_slack:

    # If you want to use an another httplug client service.
    http:
        client: httplug.client

    # The Slack API Incoming WebHooks URL.
    endpoint: 'https://hooks.slack.com/services/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'
    channel: null
    username: null
    icon: null
    link_names: false
    unfurl_links: false
    unfurl_media: true
    allow_markdown: true
    markdown_in_attachments: []
