apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  labels:
    app: labs-slack-integration
    role: backend
    version: master
  name: labs-slack-integration
  namespace: labs-slack-integration-master
spec:
  replicas: 1
  selector:
    matchLabels:
      app: labs-slack-integration
      role: backend
      version: master
  template:
    metadata:
      labels:
        app: labs-slack-integration
        role: backend
        version: master
      name: labs-slack-integration
    spec:
      containers:
      - args:
        - apachectl
        - -D
        - FOREGROUND
        env:
        - name: APP_ENV
          valueFrom:
            configMapKeyRef:
              key: APP_ENV
              name: backend-config
        - name: APP_SECRET
          valueFrom:
            configMapKeyRef:
              key: APP_SECRET
              name: backend-config
        image: eu.gcr.io/ptcs-docker-registry/labs-slack-integration:latest-master
        imagePullPolicy: Always
        name: labs-slack-integration
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: labs-slack-integration
    role: backend
    version: master
  name: labs-slack-integration
  namespace: labs-slack-integration-master
spec:
  type: ClusterIP
  ports:
  - port: 80
    protocol: TCP
    targetPort: 80
  selector:
    app: labs-slack-integration
    role: backend
    version: master