apiVersion: v1
kind: Namespace
metadata:
  name: labs-slack-integration-master
---
apiVersion: v1
kind: LimitRange
metadata:
  name: default-limit-range
  namespace: labs-slack-integration-master
spec:
  limits:
  - default:
      cpu: 300m
      memory: 512Mi
    defaultRequest:
      cpu: 0
      memory: 0
    type: Container